spring.application.name=auth
spring.config.import=optional:file:.env[.properties]

app.security.jwt.secret=${JWT_SECRET}
app.security.jwt.issuer=${JWT_ISSUER:solaria-auth}
app.security.jwt.access-token-ttl=${JWT_ACCESS_TOKEN_TTL:PT15M}
app.security.jwt.refresh-token-ttl=${JWT_REFRESH_TOKEN_TTL:P7D}
