package com.solaria.auth.enums

enum class SecurityEventType {
    USER_REGISTERED,
    LOGIN_SUCCEEDED,
    LOGIN_FAILED,
    LOGOUT,
    PASSWORD_CHANGED,
    PASSWORD_RESET_REQUESTED,
    PASSWORD_RESET_COMPLETED,
    FEDERATED_IDENTITY_LINKED,
    FEDERATED_IDENTITY_UNLINKED,
    MFA_ENABLED,
    MFA_DISABLED,
    MFA_CHALLENGE_FAILED,
    REFRESH_TOKEN_REUSED,
    SESSION_REVOKED
}
